### ISSUE TITLE
Service.Speaker is not a function

### ISSUE THREAD

**Issue by timc3** [stfnhmplr/homebridge-denon-marantz-avr#12]
I am getting the following 

`/usr/lib/node_modules/homebridge-denon/index.js:140
    this.speakerService = new Service.Speaker(this.name);
                          ^
TypeError: Service.Speaker is not a function
    at DenonAVRAccessory.getServices (/usr/lib/node_modules/homebridge-denon/index.js:140:27)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:357:36)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:245:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)`

When trying to run with homebridge 0.4.16 and it seems it installed:

 `[2/8/2017, 8:04:53 PM] Loaded plugin: homebridge-denon
[2/8/2017, 8:04:53 PM] Registering accessory 'homebridge-denon-marantz-avr.DenonMarantzAVR'`

**Comment by stfnhmplr** [comment]
hi. looks like you're using an outdated version from HAP-NodeJS. Please update the package (and homebridge) to get the full support of the ios10 service types.

**Comment by rejbbc** [comment]
Hello,

Thank you for this plugin ! 

Works great but impossible to get "speaker service" here in Europe.  The amp is displayed as a switch only.  Do you have a picture of the speaker widget in iOS 10 ?

**Comment by stfnhmplr** [comment]
Do you use the official Home App? Currently the Speaker Service is not supported there so your amp is displayed as switch only.

Try Elgatos EVE App. Looks like this:
![img_3567](https://cloud.githubusercontent.com/assets/3863403/24171337/572e8be6-0e84-11e7-9d76-2b3f29fdc57a.jpg)
