### ISSUE TITLE
Power On/Standby

### ISSUE THREAD

**Issue by danbridgland** [stfnhmplr/homebridge-denon-marantz-avr#22]
Any way to read and control the current power state?

Having read the PR’s, I saw an option for a http call, { http://10.0.0.14:8080/goform/formiPhoneAppDirect.xml?PWSTANDBY }, this worked great in the browser, but I really want it as a switch in HomeBridge.

**Comment by lswee** [comment]
I believe this is meant to work actually... looking at index.js there is getPowerState etc.

However, I am having issues with this too -

It can't seem to find whether it's on or off:

[2019-1-4 20:31:18] [Denon] Initializing DenonMarantzAVR accessory...
[2019-1-4 20:31:18] [Denon] start polling..
[2019-1-4 20:31:18] [Denon] do poll..
[2019-1-4 20:31:20] [Denon] Can't connect to device: null
[2019-1-4 20:31:20] [Denon] poll end, state: false
[2019-1-4 20:32:18] [Denon] do poll..
[2019-1-4 20:32:19] [Denon] Can't connect to device: null
[2019-1-4 20:33:18] [Denon] do poll..
[2019-1-4 20:33:31] [Denon] Can't connect to device: null


This is what happens when I toggle the switch:
[2019-1-4 20:33:37] [Denon] denon avr powered undefined
[2019-1-4 20:33:39] [Denon] denon avr powered undefined
[2019-1-4 20:33:45] [Denon] denon avr powered undefined
[2019-1-4 20:33:51] [Denon] denon avr powered undefined

The Denon stays on, but it does display on my TV screen the default volume of 35 when I toggle the switch on, so it's clearly receiving something...



The following commands do turn the receiver on/off if sent from the browser:
192.168.1.9:8080/goform/formiPhoneAppDirect.xml?PWON
192.168.1.9:8080/goform/formiPhoneAppDirect.xml?PWSTANDBY




My config is:
      {
          "accessory": "DenonMarantzAVR",
          "name": "Denon",
          "ip": "192.168.1.9",
          "port": 8080,
          "defaultInput": "CBL/SAT",
          "defaultVolume": 35,
          "doPolling": true,
          "pollingInterval": 60
      }




Edit: Volume etc. works via Eve app. So they're definitely talking.

If the device is already on I toggle on within the app, it sets it back to the default volume, but toggling off does nothing.

Toggling on when the device is off does nothing/doesn't turn it on.

**Comment by danbridgland** [comment]
Any news on this?

**Comment by stfnhmplr** [comment]
I started rewriting the entire plugin today. I will add the new speaker service (#16) and support for the second zone (#19). I will also try to support as many models as possible. This will take a few days.

**Comment by danbridgland** [comment]
Great news!  Thank you.

**Comment by siobhanellis** [comment]
I know 3D is nolonger a part of TV’s, and that you can’t test it, but could you consider adding it as an option, and defining a default option.

I’ll be happy to test for you.


Siobhan
www.lambrettaconcessionaires.com<http://www.lambrettaconcessionaires.com>

**Comment by siobhanellis** [comment]
Ignore my last 😃 wrong plug in.


Siobhan
www.lambrettaconcessionaires.com<http://www.lambrettaconcessionaires.com>

**Comment by danbridgland** [comment]
Just had a read up on the HomeKit speaker service, however it seems the long since pledged service is still not present in HomeKit as of iOS 12.1.2

@stfnhmplr, Have you found a way to add this speaker service?

**Comment by siobhanellis** [comment]
I believe it is there, just not exposed in the Homekit app. Can’t you use it in the Eve App?

Anyway, it must be coming for the new TV services that were announced in CES.


Siobhan
www.lambrettaconcessionaires.com<http://www.lambrettaconcessionaires.com>

**Comment by danbridgland** [comment]
How’s the rewrite going?  In need of any beta testers?

**Comment by lswee** [comment]
I’d be willing to help test too.

Also worth noting that with the new iOS beta a lot of TV features have been enabled:

https://twitter.com/KhaosT/status/1088678984970162176

Does the Speaker Service support selecting inputs like the TV Service does?

**Comment by stfnhmplr** [comment]
I just released a first update in the dev branch. any testers are welcome.

The Speaker Service is still not supported by Apple's Home App, but works for example with the EVE App. Selecting inputs is not possible, but the volume can be adjusted.

To test the version, you have to take the following steps:
```
git clone --single-branch --branch dev https://github.com/stfnhmplr/homebridge-denon-marantz-avr.git
cd homebridge-denon-marantz-avr
npm install
rollup -c
```

Then change your config (see readme) and restart homebridge.

**Comment by lswee** [comment]
Thank you!

The last command didn't work for me on macOS SSH'ing into a Pi:

> -bash: rollup: command not found


So I'm assuming it's not properly installed for me, because when I added it to the config (changing it to a platform as described), my homebridge crashed and said:

> Error: The requested platform 'DenonMarantzAVR' was not registered by any plugin.

**Comment by stfnhmplr** [comment]
I'm sorry. You should install rollup globally by typing `npm install -g rollup` and execute the command again.

**Comment by lswee** [comment]
Great, thank you.

It doesn't seem to be working or registering for me:

`rollup -c`

> src/index.js → dist/index.js...
> (!) node-resolve plugin: The onwrite hook used by plugin node-resolve is deprecated. The generateBundle hook should be used instead.
> created dist/index.js in 6.1s
> 
> src/accessories/MainZoneAccessory.js → dist/accessories/MainZoneAccessory.js...
> (!) node-resolve plugin: The onwrite hook used by plugin node-resolve is deprecated. The generateBundle hook should be used instead.
> created dist/accessories/MainZoneAccessory.js in 3.5s
> 
> src/accessories/SecondZoneAccessory.js → dist/accessories/SecondZoneAccessory.js...
> (!) node-resolve plugin: The onwrite hook used by plugin node-resolve is deprecated. The generateBundle hook should be used instead.
> created dist/accessories/SecondZoneAccessory.js in 1.8s


This seems to be relevant: https://github.com/egoist/rollup-plugin-postcss/issues/147

I can't find where it says onwrite to change it though.



Edit:
Before this I was having access permission issues with `npm install -g rollup` which I fixed after seeing this comment: https://github.com/tldr-pages/tldr/issues/820#issuecomment-193847014

That issue is outlined here: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

It's solved by installing a Node version manager: https://github.com/creationix/nvm#installation

**Comment by stfnhmplr** [comment]
I just added the dist files so that testing should be easier. You don't have to install rollup now.
Just delete the folder and clone the dev branch again. Or switch into the folder and fetch the latest update.

**Comment by lswee** [comment]
Thanks @stfnhmplr .

I've cloned the latest version, `npm install`:
> added 166 packages from 152 contributors and audited 1542 packages in 26.344s
> found 0 vulnerabilities

I feel like I'm missing something.. With the correct config, when I launch homebridge I get:
> The requested platform 'DenonMarantzAVR' was not registered by any plugin.

**Comment by stfnhmplr** [comment]
What directory did you clone it to? It must be the global npm modules folder. Or you have to run it in development mode, see the Homebridge ReadMe for instructions.

**Comment by paulseiler** [comment]
I literally found out about HomeBridge on Sunday. I just a couple of hours ago got it up and installed on my Synology NAS using Docker, with my first working platform for my Sony Bravia TV, and now my Denon S930H is next up. So happy I found out about this. Thank you so much for developing this and staying up to date on these HomeKit integrations <3

**Comment by paulseiler** [comment]
> What directory did you clone it to? It must be the global npm modules folder. Or you have to run it in development mode, see the Homebridge ReadMe for instructions.

So I've been tinkering with Denon plugins for a few hours. I'm working with yours at the moment. Been struggling with the getting the volume to work right. It kept crashing in a loop, unable to garnish a proper result for the "Receiver MainZone Volume power state" which was always broken at "0" ... Needed to share this ...

<img width="1225" alt="screen shot 2019-02-05 at 4 07 32 am copy" src="https://user-images.githubusercontent.com/4550851/52263430-2428c780-28fd-11e9-809c-1915135e5869.png">

... literally immediately after installing this dev version, it works!

Now I am having a different hiccup ... but everything I want this accessory button to do is working on some level. Haha. It's bugging out a bit but I can send logs if you're interested.

It turns my Denon S930H On & Off, as well as changes the volume! I left out the "...max100" option as my entire family is used to the Denon based volume numbers on our receivers already. IT ALL WORKS WITH ONE BUTTON 💃 !

Here's a screenshot of the logs when it died ... ha.

<img width="922" alt="screen shot 2019-02-05 at 4 35 13 am" src="https://user-images.githubusercontent.com/4550851/52264420-90a4c600-28ff-11e9-9284-9f34e29d7d94.png">

<img width="920" alt="screen shot 2019-02-05 at 4 35 25 am" src="https://user-images.githubusercontent.com/4550851/52264425-94384d00-28ff-11e9-8d61-c78bc141dfb3.png">

My config:

        {
          "accessory": "marantz-volume",
          "name": "Denon Volume",
          "host": "static.denon.ip.address:8080",
          "maxVolume":  75,
          "controlPower": true,
          "controlMute": true
    }

–––––

Off:

![img_3961](https://user-images.githubusercontent.com/4550851/52265804-ddd66700-2902-11e9-91aa-d9b8f5f76ae7.jpeg)

![img_3970](https://user-images.githubusercontent.com/4550851/52265613-7f10ed80-2902-11e9-8044-248baba8b016.jpeg)

–––––

On:
![img_3967](https://user-images.githubusercontent.com/4550851/52265598-76201c00-2902-11e9-8045-194c8f9acc32.jpeg)

![img_3973](https://user-images.githubusercontent.com/4550851/52265623-87692880-2902-11e9-8615-b9fb6ddc10ea.jpeg)

![img_3974](https://user-images.githubusercontent.com/4550851/52265636-8f28cd00-2902-11e9-9955-ece8427f1344.jpeg)

–––––

Change Volume to 20%:
![img_3976](https://user-images.githubusercontent.com/4550851/52265647-94861780-2902-11e9-883c-a9d114b3e55b.jpeg)

![img_3975](https://user-images.githubusercontent.com/4550851/52265661-98b23500-2902-11e9-8739-eb329e6917b1.jpeg)

–––––

Going to play around with the options for ...

          "doPolling": true,
          "pollingInterval": 60

... and see if that won't fix some connection quirks.

Cheers <3

**Comment by lswee** [comment]
> What directory did you clone it to? It must be the global npm modules folder. Or you have to run it in development mode, see the Homebridge ReadMe for instructions.

Thanks @stfnhmplr, getting this up and running has actually helped me improve my setup in general!

I'm now getting this:

> [2/5/2019, 8:17:13 PM] Loaded plugin: homebridge-denon-marantz-avr
> [2/5/2019, 8:17:13 PM] Registering platform 'homebridge-denon.DenonMarantzAVR'
> [2/5/2019, 8:17:14 PM] [Speakers] Initializing DenonMarantzAVR platform...
> [2/5/2019, 8:17:14 PM] [Speakers] Not connected to AVR. Trying again...
> 
>     throw err; // Unhandled 'error' event
>     ^
> 
> Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Cannot connect')
>     at Telnet.emit (events.js:186:17)
>     at Socket.socket.setTimeout (/home/pi/.nvm/versions/node/v11.9.0/lib/node_modules/homebridge-denon-marantz-avr/node_modules/telnet-client/lib/index.js:76:16)
>     at Object.onceWrapper (events.js:285:13)
>     at Socket.emit (events.js:197:13)
>     at Socket._onTimeout (net.js:447:8)
>     at listOnTimeout (timers.js:327:15)
>     at processTimers (timers.js:271:5)

**Comment by stfnhmplr** [comment]
@paulseiler Thanks for trying. 

>    {
      "accessory": "marantz-volume",
      "name": "Denon Volume",
      "host": "static.denon.ip.address:8080",
      "maxVolume":  75,
      "controlPower": true,
      "controlMute": true
}

This config is not for this plugin 😉 Take a look at the readme of the [dev branch](https://github.com/stfnhmplr/homebridge-denon-marantz-avr/tree/dev) for an example.

>  "doPolling": true,
      "pollingInterval": 60

Since the new version connects over telnet, there's no polling needed anymore. If you change the volume by hand, your accessories should receive the new state immediately.

**Comment by stfnhmplr** [comment]
@lswee Looks like an connection issue. Did you update your config as shown in the [example](https://github.com/stfnhmplr/homebridge-denon-marantz-avr/tree/dev)?
Is the Denon accessible in the network? You can try it with ping. You can also check if port 23 is open. It should report something like `Open TCP Port: 	23     		telnet`

**Comment by lswee** [comment]
Thanks for your reply @stfnhmplr 

My config is:
```
        {
          "platform": "DenonMarantzAVR",
          "name": "Speakers",
          "host": "192.168.1.9",
          "maxVolume": 70
        }
```

Should that work?

My Denon should be available over the network... the AVR Remote works and I can AirPlay to it.

Also the following commands work:
`192.168.1.9:8080/goform/formiPhoneAppDirect.xml?PWON`
`192.168.1.9:8080/goform/formiPhoneAppDirect.xml?PWSTANDBY`

I'm unsure how to check if port 23 is open however... I've done a simple ping and it worked.

I've also tried my config with :8080 following the IP.

**Comment by lswee** [comment]
I've looked into this further, it seems telnet does not come as standard with Raspbian...

I've now installed it using:
`sudo apt-get install telnet`

I can connect to the Denon, although it kicks me off after a few seconds, I'm not sure as to why.

`telnet 192.168.1.9 8080`
> Trying 192.168.1.9...
> Connected to 192.168.1.9.
> Escape character is '^]'.
> Connection closed by foreign host.

I'm still getting the following error when running homebridge:
> Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Cannot connect')
>     at Telnet.emit (events.js:186:17)
>     at Socket.socket.setTimeout (/home/pi/.nvm/versions/node/v11.9.0/lib/node_modules/homebridge-denon-marantz-avr/node_modules/telnet-client/lib/index.js:76:16)


Edit:
I don't get booted off when I don't use the port i.e. `telnet 192.168.1.9`

I'm not sure exactly what I'm looking at when that's running.
There a lines changing quickly, two I saw started with OPINFASP and SSAST followed by a long string.

However, again when I launch homebridge (whether I include the port or not), I get the above error.

I've also since tried `npm install -g telnet`, but I'm not sure if I should have done that. It doesn't seem to have made a difference.

**Comment by lswee** [comment]
@stfnhmplr I've looked at this again. Using `telnet 192.168.1.9` I can connect to my receiver. Sending `PWON` turns it on and `PWSTANDBY` turns it off. So it seems telnet is working on my Pi 3.

However, running `homebridge` with the config as mentioned (in my second my recent post above), I'm still getting the error as described in the most recent post above.

Edit:
I've found these two posts which reference a similar error -
https://github.com/mkozjak/node-telnet-client/issues/121
https://github.com/cgarwood/mpc-control/issues/12

I'm not sure if that'll be helpful? I'm a bit stumped now. Willing to help and test, but not sure where else to look with this one.

**Comment by stfnhmplr** [comment]
@lswee Thanks, but there's no need for you to pick out those links. They don't help me. Installing other packages doesn't help either. Your config looks fine.

The default telnet port is 23, so you don't need to specify a port. Are you using another application on the network that might be blocking the connection? For example, an app for your smartphone that also uses Telnet to connect to your Denon.

Anyway, I pushed a few small changes, maybe they will help with troubleshooting. Please show the full log so I can better see when the error occurs. This should look something like this

```
[...]
[2019-2-17 10:31:20] [Denon LivingRoom] Initializing DenonMarantzAVR platform...
[2019-2-17 10:31:20] [Denon LivingRoom] Not connected to AVR. Trying again...
[2019-2-17 10:31:22] [Denon LivingRoom] Cannot connect
[2019-2-17 10:31:22] [Denon LivingRoom] lost connection to 192.168.1.11
[2019-2-17 10:31:22] [Denon LivingRoom] connected to 192.168.1.11
[2019-2-17 10:31:22] [Denon LivingRoom] connected to AVR (192.168.1.11)
[2019-2-17 10:31:22] [Denon LivingRoom] send command PW?
[2019-2-17 10:31:22] [Denon LivingRoom] send command MU?
[2019-2-17 10:31:22] [Denon LivingRoom] send command MV?
[2019-2-17 10:31:22] [Denon LivingRoom] send command Z2?
[2019-2-17 10:31:22] [Denon LivingRoom] send command Z2MU?
[2019-2-17 10:31:22] [Denon LivingRoom] send command Z2?
[2019-2-17 10:31:22] [Denon LivingRoom] Initializing platform accessory 'Denon LivingRoom Main Zone'...
[2019-2-17 10:31:22] [Denon LivingRoom] Initializing platform accessory 'Denon LivingRoom 2nd Zone'...
[2019-2-17 10:31:23] [Denon LivingRoom] received response: PWON
[2019-2-17 10:31:23] [Denon LivingRoom] received response: MUOFF
[2019-2-17 10:31:23] [Denon LivingRoom] received response: MV345
[...]
```

**Comment by danbridgland** [comment]
Hey Stfnhmplr,

With the latest HomeKit offerings from Apple for TV support in the iOS 12.2 betas, would it be feasible to present Denon/Marantz AV amps as a TV, thereby allowing the switching of the device on/off and selecting a source all within the same HomeKit accessory?

**Comment by lswee** [comment]
@stfnhmplr thank you very much.

Telnet works for me as expected:
`telnet 192.168.1.9`
> Trying 192.168.1.9...
> Connected to 192.168.1.9.
> Escape character is '^]'.
`PWON`
`PWSTANDBY`

But running `homebridge` doesn't:
> [2/18/2019, 10:11:01 PM] ---
> [2/18/2019, 10:11:01 PM] [Speakers] Initializing DenonMarantzAVR platform...
> [2/18/2019, 10:11:01 PM] [Speakers] Not connected to AVR. Trying again...
> [2/18/2019, 10:11:02 PM] [Speakers] Cannot connect
> [2/18/2019, 10:11:02 PM] [Speakers] Cannot connect
> [2/18/2019, 10:11:03 PM] [Speakers] Not connected to AVR. Trying again...
> [2/18/2019, 10:11:03 PM] [Speakers] Cannot connect
> [2/18/2019, 10:11:04 PM] [Speakers] Cannot connect
> [2/18/2019, 10:11:05 PM] [Speakers] Not connected to AVR. Trying again...
> [2/18/2019, 10:11:05 PM] [Speakers] Cannot connect
> [2/18/2019, 10:11:06 PM] [Speakers] Cannot connect
> [2/18/2019, 10:11:06 PM] [Speakers] Cannot connect
> [2/18/2019, 10:11:07 PM] [Speakers] Not connected to AVR. Trying again...
And that repeats over and over.

I've turned off my phone and rebooted everything, so don't think anything else will be taking up that communication channel and running telnet on its own does work and turns my Denon on/off etc.

In an above comment you can see that when I ran `homebridge`, the error referred to 
> /home/pi/.nvm/versions/node/v11.9.0/lib/node_modules/homebridge-denon-marantz-avr/node_modules/telnet-client/lib/index.js:76:16

Could this be a different version of telnet (or one with different settings/permissions) than the one it uses when just running `telnet`?

**Comment by stfnhmplr** [comment]
Yeah, it's differnet but Telnet was just a test if your AVR is addressable.
Did you already fetch the latest update? Which AVR model do you have?

**Comment by lswee** [comment]
Yes, I just installed the latest version again, getting the same results with "Not connected to AVR. Trying again..." and "Cannot connect"

I have a Denon AVRX2500H

**Comment by stfnhmplr** [comment]
I'm sorry. My fault. I think i've found the issue. Please fetch the latest update from the dev branch and try again. it should work now.

**Comment by lswee** [comment]
Okay, thanks.

I'm getting "throw new Error("Attempting to register a platform '" + fullName + "' which has already been registered!");"

I didn't get this when I installed over the top last time.

I'm doing:
```
cd /home/pi/.nvm/versions/node/v11.10.0/lib/node_modules/
sudo rm -rf homebridge-denon-marantz-avr
git clone --single-branch --branch dev https://github.com/stfnhmplr/homebridge-denon-marantz-avr.git
cd homebridge-denon-marantz-avr
npm install -g
```

Anything you can see wrong with that?

In the node_modules folder I can see homebridge-denon-marantz-avr and homebridge-denon (which is a different colour), should there be two?

**Comment by stfnhmplr** [comment]
That‘s probably because there is an old version in `/usr/local/lib/node_modules`
The platform should be only installed once.

**Comment by lswee** [comment]
Hm, I can't find anything there...
"cd: /usr/local/lib/node_modules: No such file or directory"

**Comment by stfnhmplr** [comment]
You can run npm list -g to see where global libraries are installed.
Can’t really help here, it‘s related to a duplicate platform.
Do you use another plugin with the same platform name?

**Comment by lswee** [comment]
Sorry, I don't think so...
https://pastebin.com/peftc4bG

Edit: Fixed it with npm -g un homebridge-denon-marantz-avr

The plugin seems to be working now, thanks!

**Comment by lswee** [comment]
Yep, I have been using this for a couple of hours now and it’s all good. Thanks so much!

I can control the volume with the Eve app, but not within Apple’s Home. I’m running the latest iOS beta and in that hey’ve enabled TVs. My Sony TV works really well, I can change inputs and control it using Apple’s Remote app and widget.

Have Apple enabled their speaker service to enable control of volume? I know people found a way of making them appear as a light (with brightness being volume), but I was wondering if they’ve now enabled something more official for speakers? Would really like to be able to control everything within one app/Siri.

**Comment by stfnhmplr** [comment]
I know. Apples Home App does not support the speaker accessory. It's possible to control the volume as light, but I don't think that makes much sense. For example, if you say "Siri, dim the light in the living room to 100%" it could get very loud 😉 
I haven't tried the beta yet but the new tv accessory sounds promising. But first things first: I will publish the current version to npm.

**Comment by danbridgland** [comment]
The 12.2 betas seem to offer a perfect fit for AVR’s, basically a TV without the display.  All other aspects fit.

**Comment by lswee** [comment]
Great, well thanks for getting this working, really happy.

I agree about the fit, but I don’t know how it would work technically. With my Sony TV I can choose inputs and I can also control it using the Remote app and Widget. I haven’t however noticed a volume control (I may be wrong), so wouldn’t call it a ‘perfect’ fit.

**Comment by danbridgland** [comment]
Now you mention it, I think you’re right, so far there is no volume control,  I don’t think there’s any explanation as to why as yet?

**Comment by danbridgland** [comment]
I remembered reading a 9to5Mac article where volume control was specificly mentioned, https://9to5mac.com/2019/01/31/homekit-tv-home-app-ios-12-2/  Zac said on that post that the Homebridge LG accessory he tested allowed the volume control to be set from control centre whilst on the mini remote app using the side buttons.

Presumably if volume control is set via HDMI-CEC it shouldn’t matter where the volume control is triggered, be it the TV or AVR?

So it seems 12.2 is still a good fit, though I’d concede it’s not yet perfect.

**Comment by lswee** [comment]
Ah, interesting. Well that would be perfect!

**Comment by lswee** [comment]
A super strange occurrence a month ago...

I could control the volume using my phone and it worked. Seemed to be a built in AirPlay thing. It just appeared and worked, but it hasn't shown up again since...
