### ISSUE TITLE
Homebridge reboot loop when Telnet can’t reach Receiver (v0.4.0)

### ISSUE THREAD

**Issue by th3cube** [stfnhmplr/homebridge-denon-marantz-avr#27]
When the Receiver is offline (No Network Connection) and Homebridge reboots the plug-in crashes Homebridge and Homebridge goes into a Reboot Loop.

`[Denon] Error: connect EHOSTUNREACH x.x.x.x:23
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: 'x.x.x.x',
  port: 23 }`

`[Denon]Cannot connect
Denon]{ Error: connect EHOSTUNREACH x.x.x.x:23
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: 'x.x.x.x',
  port: 23
`

Plugin Version 0.4.0

**Comment by luc-ass** [comment]
Ok! Now I started to have the same problem... strange...

**Comment by galzil** [comment]
Same here

**Comment by YRRK** [comment]
I'm getting the ! everytime while the plugin seems to continue working.... Could it be that the status polling goes to fast and the plug-in doesn't get an answer from the AVR? There should be a 30ms delay between telnet command requests to the AVR according to the Denon AVR telnet commands manual.
