### ISSUE TITLE
Unable to setup Marantz

### ISSUE THREAD

**Issue by F0t0gy** [stfnhmplr/homebridge-denon-marantz-avr#41]
Hey there!

Newbie here, i want to make my stoopid Marantz:[M-CR603] a little smart and make it turn on via Siri, i installed the plugin and tried entering everything i could but i get the error:

`TypeError: this.config.accessories is not iterable
    at DenonMarantzAVRPlatform.discoverAVR (/homebridge/node_modules/homebridge-denon-v3/src/platform.ts:91:64)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-denon-v3/src/platform.ts:42:18)
    at HomebridgeAPI.emit (node:events:525:35)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/homebridge/node_modules/homebridge/src/server.ts:190:14)`

My configeration is:

`{
    "bridge": {
        "name": "Homebridge ****",
        "username": "Admin",
        "port": ******,
        "pin": "*********"
    },
    "description": "just an example config",
    "platforms": [
        {
            "platform": "MarantzAVR",
            "name": "Marantz Max",
            "host": "***",
            "maxVolume": 60,
            "defaultVolume": 20,
            "defaultInput": "AUX4",
            "secondZone": false
        }
    ],
    "platform": "denon-marantz-avr"
}`

Hope you can help me

**Comment by luc-ass** [comment]
Hey there. I've had a look at it and suspect, that this plugin won't work for you, because your marantz is not an AV-Reciever.
