### ISSUE TITLE
This callback function has already been called by someone else; it can only be called one time.

### ISSUE THREAD

**Issue by christophedelanghe** [stfnhmplr/homebridge-denon-marantz-avr#9]
This used to work fine for a long time. Recently I get this error when I try to activate the denon receiver.

Any idea?

my config:

{
	"accessory": "DenonMarantzAVR",
	"name": "CaveDenon",
	"ip": "192.168.0.234",
	"type" : "Denon",
	"defaultInput": "TUNER",
	"defaultVolume": 35,
	"minVolume": 10,
	"maxVolume": 75
},

the error:

[2016-12-03 11:19:43] [CaveDenon] { [Error: connect EHOSTUNREACH 192.168.0.234:80]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.0.234',
  port: 80 }
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at DenonAVRAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-denon/index.js:92:13)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon/lib/denon.js:95:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-denon/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-denon/node_modules/request/request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

**Comment by stfnhmplr** [comment]
Sorry for my late reply. Is the error still current? Looks like a network error. Can you ping the device?

**Comment by christophedelanghe** [comment]
It was indeed a network error. Wrong IP in the config file due to DHCP ... thx for your response!
